In [ ]:
import numpy as np
list1=[1,2,3,4,5]
arr01=np.array(list1)
arr02=np.array([10,20,30,'a'])
arr01
arr02
# print (arr01)
# print(arr02)




array([10, 20, 30])

In [5]:
import numpy as np
arr1=np.zeros(10)
print(arr1)
arr2=np.ones(10)
print(arr2)
arr3=np.zeros_like(arr2)
print(arr3)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
a=np.random.random((10,2))     #10행2열
print(a)

[[0.84024439 0.81925453]
 [0.61849772 0.87547712]
 [0.54151944 0.98041378]
 [0.61537612 0.02509258]
 [0.02657789 0.10899866]
 [0.48195487 0.02121846]
 [0.11114712 0.81989206]
 [0.1073156  0.95195993]
 [0.85789755 0.64510754]
 [0.705739   0.87482868]]


In [7]:
a=np.random.rand(3,3)
print(a)

[[0.30127987 0.28033974 0.25529395]
 [0.27401854 0.81284581 0.17838123]
 [0.45329538 0.85305547 0.5928933 ]]


In [8]:
a=np.random.randint(1,100,10)
print(a)

[ 4 33 58 67  7 36  1 44 98 12]


In [ ]:
a=np.arange(16)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
1
(16,)
16
int64
8


In [13]:
import numpy as np

a = np.arange(16).reshape(4,4)  # 4x4 배열 생성
print(a)

print(a[2][2])      # 3번째 행, 3번째 열 값
print(a[::2, -1])   # 행을 2칸씩 건너뛰며 마지막 열 값

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
10
[ 3 11]


In [14]:
a1=np.arange(6)
print(a1)
print(a1[0:3])
print(a1[1:])
print(a1[-2:])
print(a1[:-3])
print(a1[::2])
print(a1[::-1])

[0 1 2 3 4 5]
[0 1 2]
[1 2 3 4 5]
[4 5]
[0 1 2]
[0 2 4]
[5 4 3 2 1 0]


In [15]:
a=np.arange(1,6)
print(a)
b=[True,False,False,True,False]
print(a[b])

[1 2 3 4 5]
[1 4]


In [16]:
print(a[a<3])
print(a[a>=3])
print(a[a%2==1])

[1 2]
[3 4 5]
[1 3 5]


In [18]:
print(a[(a>4) | (a<2)])
print(a[(a>=2) & (a<=4)])
print(a[~(a<3)])

[1 5]
[2 3 4]
[3 4 5]


In [5]:
# dataframe
import pandas as pd
import numpy as np
arr=np.arange(12).reshape(4,3)     #2차원짜리 배열 reshape
df=pd.DataFrame(arr, columns=['A', 'B', 'C'])
df

A   B   C
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [7]:
name=['홍길동','진영랑','김유하','이정은']
score=[90, 85, 90, 80]
depts=['컴공', '수학', '영문', '국문']
df1=pd.DataFrame({'name':name, 'score':score,'depts':depts})
df1

name  score depts
0  홍길동     90    컴공
1  진영랑     85    수학
2  김유하     90    영문
3  이정은     80    국문

In [8]:
data=[name,score,depts]
data

[['홍길동', '진영랑', '김유하', '이정은'], [90, 85, 90, 80], ['컴공', '수학', '영문', '국문']]

In [12]:
df2=pd.DataFrame(data).T        #dataframe 'T'
df2.columns=['name','score','depts']
df2

name score depts
0  홍길동    90    컴공
1  진영랑    85    수학
2  김유하    90    영문
3  이정은    80    국문

In [20]:
df2.to_csv("data/student.csv", index=False) #index=False index를 안불러옴. dataframe은 index 자동 불러옴

In [ ]:
df2_1=pd.read_csv('data/student.csv')       #index_col=0
df2_1

name  score depts
0  홍길동     90    컴공
1  진영랑     85    수학
2  김유하     90    영문
3  이정은     80    국문

In [17]:
df3=pd.read_csv("data/mobile.csv")   
df3

Brand   Color  price
0  Samsung   Black    100
1       LG    Gold     70
2    Apple  Silver    150
3    Apple    Gray    120

In [14]:
df4=pd.read_excel("data/code.xlsx")    #파일 깨지면 encoding 추가
df4

국적코드  국적명
0  A01  필리핀
1  A02   일본
2  A03   미국
3  A04   중국
4  A05   호주
5  A06  베트남
6  A07  스위스
7  A99   기타

In [ ]:
df5=pd.read_csv("data/score.csv",header=None)         #header 교체    header=None으로 1,2로 바꿈
df5.columns=['name','score','major']                   #header를 list로 만들어 추가
df5

name  score major
0  홍길동     85    컴공
1  진영랑     80    수학
2  김유하     85    영어
3  이정은     90    국문

In [31]:
df6=pd.read_excel("data/score.xlsx")
df6

이름  점수  전공
0  홍길동  90  컴공
1  김길동  80  컴멀
2  이길동  70  수학

In [32]:
df7=pd.read_csv('data/bank.csv')
df7

job  education  balance  duration    y
0        management   tertiary     2143       261   no
1        technician  secondary      265       348   no
2       blue-collar  secondary       -7       365   no
3        technician  secondary       -3      1666   no
4        technician  secondary     -103       145   no
...             ...        ...      ...       ...  ...
7229       services  secondary      199       173   no
7230  self-employed   tertiary      159       449  yes
7231     management   tertiary      138       162   no
7232     management   tertiary     1428       333   no
7233     technician  secondary      505       386  yes

[7234 rows x 5 columns]

In [ ]:
df7.head(10)            #head, tail   처음, 끝 데이터

job  education  balance  duration    y
0   management   tertiary     2143       261   no
1   technician  secondary      265       348   no
2  blue-collar  secondary       -7       365   no
3   technician  secondary       -3      1666   no
4   technician  secondary     -103       145   no
5      retired   tertiary      100       528   no
6   technician  secondary     1205       158   no
7   management  secondary      282       154   no
8     services  secondary       91       349   no
9       admin.  secondary       45      1467  yes

In [34]:
df7.index
df7.columns

Index(['job', 'education', 'balance', 'duration', 'y'], dtype='object')

In [ ]:
df7.describe()    #요약

balance     duration
count   7234.000000  7234.000000
mean    1374.912911   262.875311
std     3033.882933   268.921065
min    -3313.000000     0.000000
25%       74.000000   103.000000
50%      453.500000   183.000000
75%     1470.750000   321.750000
max    81204.000000  3366.000000

In [36]:
print(df7['balance'].mean())
print(df7['balance'].max())
print(df7['balance'].min())
print(df7['balance'].sum())
print(df7['balance'].median())

1374.9129112524192
81204
-3313
9946120
453.5


In [38]:
df7.sort_values(by='balance', ascending=True, inplace=True)      #inplace=True  더해줌
df7

job  education  balance  duration    y
298   self-employed   tertiary    -3313       153   no
2289     management   tertiary    -2282       301   no
2506     management   tertiary    -1884       193   no
3981   entrepreneur  secondary    -1882        17   no
1937     technician  secondary    -1680        92   no
...             ...        ...      ...       ...  ...
6692     management   tertiary    37378       146   no
2361     management   tertiary    38279       225   no
4353       services  secondary    57435       319   no
2025    blue-collar  secondary    58932       339   no
6926        retired  secondary    81204       390  yes

[7234 rows x 5 columns]

In [39]:
df7.sort_index(inplace=True)
df7

job  education  balance  duration    y
0        management   tertiary     2143       261   no
1        technician  secondary      265       348   no
2       blue-collar  secondary       -7       365   no
3        technician  secondary       -3      1666   no
4        technician  secondary     -103       145   no
...             ...        ...      ...       ...  ...
7229       services  secondary      199       173   no
7230  self-employed   tertiary      159       449  yes
7231     management   tertiary      138       162   no
7232     management   tertiary     1428       333   no
7233     technician  secondary      505       386  yes

[7234 rows x 5 columns]

In [42]:
df7['job'].value_counts(ascending=True)     #value_counts(어떤 열의 값을 가지고 정렬해주는) 
#예; 회원등급(골드, 실버, 브론즈)의 수 가 얼마인가


job
student           153
housemaid         208
unemployed        223
entrepreneur      239
self-employed     256
retired           351
services          661
admin.            834
technician       1206
blue-collar      1499
management       1560
Name: count, dtype: int64

In [43]:
df7[['job','balance']]

job  balance
0        management     2143
1        technician      265
2       blue-collar       -7
3        technician       -3
4        technician     -103
...             ...      ...
7229       services      199
7230  self-employed      159
7231     management      138
7232     management     1428
7233     technician      505

[7234 rows x 2 columns]

In [ ]:
df7.job.unique()           #unique(중복 제거)

array(['management', 'technician', 'blue-collar', 'retired', 'services',
       'admin.', 'entrepreneur', 'self-employed', 'unemployed', 'student',
       nan, 'housemaid'], dtype=object)

In [46]:
df7.dtypes

job          object
education    object
balance       int64
duration      int64
y            object
dtype: object

In [47]:
df7['balance'].dtype

dtype('int64')

In [49]:
job=df7.job
print(type(job))

<class 'pandas.core.series.Series'>


In [51]:
data=df7[['job','balance']]
print(type(data))

<class 'pandas.core.frame.DataFrame'>


In [ ]:
df7.loc[:5:2,:]        #슬라이싱

job  education  balance  duration   y
0   management   tertiary     2143       261  no
2  blue-collar  secondary       -7       365  no
4   technician  secondary     -103       145  no

In [54]:
df7.loc[:5:2,['job','balance']]

job  balance
0   management     2143
2  blue-collar       -7
4   technician     -103

In [55]:
df7.iloc[:,:3]

job  education  balance
0        management   tertiary     2143
1        technician  secondary      265
2       blue-collar  secondary       -7
3        technician  secondary       -3
4        technician  secondary     -103
...             ...        ...      ...
7229       services  secondary      199
7230  self-employed   tertiary      159
7231     management   tertiary      138
7232     management   tertiary     1428
7233     technician  secondary      505

[7234 rows x 3 columns]

In [57]:
df=pd.read_csv("data/weather.csv")
df

date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [58]:
df.set_index('date',inplace=True)
df

temp  max_wind  mean_wind
date                                 
2010-08-01  28.7       8.3        3.4
2010-08-02  25.2       8.7        3.8
2010-08-03  22.1       6.3        2.9
2010-08-04  25.3       6.6        4.2
2010-08-05  27.2       9.1        5.6
...          ...       ...        ...
2020-07-27  22.1       4.2        1.7
2020-07-28  21.9       4.5        1.6
2020-07-29  21.6       3.2        1.0
2020-07-30  22.9       9.7        2.4
2020-07-31  25.7       4.8        2.5

[3653 rows x 3 columns]

In [60]:
# df.set_index('date', inplace=True)
df.loc['2010-08-01':'2010-08-10',:]

temp  max_wind  mean_wind
date                                 
2010-08-01  28.7       8.3        3.4
2010-08-02  25.2       8.7        3.8
2010-08-03  22.1       6.3        2.9
2010-08-04  25.3       6.6        4.2
2010-08-05  27.2       9.1        5.6
2010-08-06  26.8       9.8        8.0
2010-08-07  27.5       9.1        5.0
2010-08-08  26.6       5.9        4.0
2010-08-09  26.9       5.1        3.1
2010-08-10  25.6      10.2        5.5

In [61]:
df.loc[df.temp>30,:]
df.loc[df.mean_wind>=7,:]

temp  max_wind  mean_wind
date                                 
2010-08-06  26.8       9.8        8.0
2010-08-15  24.5      16.9       10.3
2010-09-07  20.7      12.7        7.6
2010-09-10  24.8      11.1        7.2
2010-09-22  15.4      11.7        7.9
...          ...       ...        ...
2020-04-25  13.4      14.3        9.9
2020-05-01  23.1      13.1        7.9
2020-07-01  16.8      19.7        8.7
2020-07-14  17.8      12.7        9.4
2020-07-20  23.0      11.2        7.3

[257 rows x 3 columns]

bank에서 balance 2000이상인 사람을 표시하라

In [63]:
df7=pd.read_csv("data/bank.csv")
df7.loc[df7.balance>=2000,:]

job  education  balance  duration    y
0       management   tertiary     2143       261   no
26         retired  secondary     2127       172   no
85      technician        NaN     2106       168   no
86      management   tertiary     2877       278   no
88     blue-collar    primary     2226       158   no
...            ...        ...      ...       ...  ...
7217       retired    primary     2693        83   no
7219    technician        NaN    11115       189   no
7220    technician  secondary     2779       324   no
7224       retired    primary     3738       301   no
7228  entrepreneur  secondary     2543       357  yes

[1357 rows x 5 columns]

In [65]:
df7.loc[
    (df7.balance > 10000) & (df7.duration >= 300),
    ['job', 'balance', 'duration']
]


job  balance  duration
358      technician    24299       704
798     blue-collar    29050       563
1046     technician    10865       350
1089        student    16173       489
1661      housemaid    13292      1238
1789       services    20541       501
2025    blue-collar    58932       339
3067     management    13021       425
3123     management    10273       359
3140     management    15904       504
3282     technician    23919       384
3935  self-employed    10653       336
3971   entrepreneur    11887      1181
4186       services    11512       301
4274     management    19391       391
4279    blue-collar    12519       615
4353       services    57435       319
4360     management    22520       579
4855     management    14344       358
5058    blue-collar    13408       647
5177    blue-collar    13654       528
5182    blue-collar    10045       617
5403     management    10281       400
5850     management    23552       507
6194     technician    13460      1068
6493        student    10086       475
6546      housemaid    11219       699
6793     management    11891       821
6849        retired    23421       432
6926        retired    81204       390
6944      housemaid    26965       654
7070  self-employed    10861       336

In [66]:
df[df['max_wind'].isna()]

temp  max_wind  mean_wind
date                                 
2012-02-11  -0.7       NaN        NaN
2012-02-12   0.4       NaN        NaN
2012-02-13   4.0       NaN        NaN
2019-04-19   7.8       NaN        2.3

In [67]:
df1=df1.dropna()
df1.isnull().sum()

name     0
score    0
depts    0
dtype: int64

In [68]:
df.info()
df.isnull().sum()
df2=df.dropna()

<class 'pandas.core.frame.DataFrame'>
Index: 3653 entries, 2010-08-01 to 2020-07-31
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   temp       3653 non-null   float64
 1   max_wind   3649 non-null   float64
 2   mean_wind  3647 non-null   float64
dtypes: float64(3)
memory usage: 243.2+ KB


In [69]:
df4=df.fillna(df.mean())
df4.isnull().sum()

temp         0
max_wind     0
mean_wind    0
dtype: int64

In [76]:
import pandas as pd

dust = pd.read_excel('data/dust1.xlsx')
dust.head(5)


지역     망   측정소코드 측정소명        측정일시    SO2   CO     O3    NO2  PM10  \
0  서울 송파구  도시대기  111273  송파구  2021040101  0.004  1.0  0.002  0.066    50   
1  서울 송파구  도시대기  111273  송파구  2021040102  0.004  0.8  0.002  0.058    48   
2  서울 송파구  도시대기  111273  송파구  2021040103  0.004  0.8  0.002  0.055    44   
3  서울 송파구  도시대기  111273  송파구  2021040104  0.003  0.8  0.002  0.055    40   
4  서울 송파구  도시대기  111273  송파구  2021040105  0.004  0.8  0.002  0.053    38   

   PM25                주소  
0    18  서울 송파구 백제고분로 236  
1    20  서울 송파구 백제고분로 236  
2    20  서울 송파구 백제고분로 236  
3    20  서울 송파구 백제고분로 236  
4    17  서울 송파구 백제고분로 236

In [86]:
dust = pd.read_excel('data/dust1.xlsx')
dust.columns = dust.columns.str.strip()
dust


지역     망   측정소코드 측정소명        측정일시    SO2   CO     O3    NO2  PM10  \
0   서울 송파구  도시대기  111273  송파구  2021040101  0.004  1.0  0.002  0.066    50   
1   서울 송파구  도시대기  111273  송파구  2021040102  0.004  0.8  0.002  0.058    48   
2   서울 송파구  도시대기  111273  송파구  2021040103  0.004  0.8  0.002  0.055    44   
3   서울 송파구  도시대기  111273  송파구  2021040104  0.003  0.8  0.002  0.055    40   
4   서울 송파구  도시대기  111273  송파구  2021040105  0.004  0.8  0.002  0.053    38   
5   서울 송파구  도시대기  111273  송파구  2021040106  0.004  0.7  0.002  0.051    38   
6   서울 송파구  도시대기  111273  송파구  2021040107  0.003  0.7  0.003  0.052    38   
7   서울 송파구  도시대기  111273  송파구  2021040108  0.004  0.8  0.004  0.057    42   
8   서울 송파구  도시대기  111273  송파구  2021040109  0.004  0.6  0.014  0.046    45   
9   서울 송파구  도시대기  111273  송파구  2021040110  0.003  0.4  0.028  0.033    44   
10  서울 송파구  도시대기  111273  송파구  2021040111  0.003  0.3  0.048  0.014    38   
11  서울 송파구  도시대기  111273  송파구  2021040112  0.003  0.3  0.053  0.012    39   
12  서울 송파구  도시대기  111273  송파구  2021040113  0.003  0.3  0.056  0.010    44   
13  서울 송파구  도시대기  111273  송파구  2021040114  0.003  0.3  0.057  0.011    42   
14  서울 송파구  도시대기  111273  송파구  2021040115  0.003  0.3  0.057  0.013    44   
15  서울 송파구  도시대기  111273  송파구  2021040116  0.003  0.3  0.060  0.012    45   
16  서울 송파구  도시대기  111273  송파구  2021040117  0.003  0.4  0.058  0.015    59   
17  서울 송파구  도시대기  111273  송파구  2021040118  0.003  0.4  0.052  0.018    68   
18  서울 송파구  도시대기  111273  송파구  2021040119  0.003  0.4  0.049  0.017    59   
19  서울 송파구  도시대기  111273  송파구  2021040120  0.003  0.4  0.045  0.019    48   
20  서울 송파구  도시대기  111273  송파구  2021040121  0.003  0.4  0.047  0.016    44   
21  서울 송파구  도시대기  111273  송파구  2021040122  0.003  0.4  0.046  0.016    41   
22  서울 송파구  도시대기  111273  송파구  2021040123  0.003  0.4  0.043  0.017    46   
23  서울 송파구  도시대기  111273  송파구  2021040124  0.002  0.4  0.047  0.013    46   
24  서울 송파구  도시대기  111273  송파구  2021040201  0.003  0.3  0.048  0.011    44   
25  서울 송파구  도시대기  111273  송파구  2021040202  0.003  0.3  0.049  0.010    45   
26  서울 송파구  도시대기  111273  송파구  2021040203  0.003  0.3  0.051  0.009    47   
27  서울 송파구  도시대기  111273  송파구  2021040204  0.003  0.3  0.050  0.009    45   
28  서울 송파구  도시대기  111273  송파구  2021040205  0.002  0.3  0.050  0.010    44   
29  서울 송파구  도시대기  111273  송파구  2021040206  0.003  0.3  0.044  0.015    42   
30  서울 송파구  도시대기  111273  송파구  2021040207  0.002  0.4  0.039  0.020    40   
31  서울 송파구  도시대기  111273  송파구  2021040208  0.003  0.4  0.030  0.031    43   

    PM25                주소  
0     18  서울 송파구 백제고분로 236  
1     20  서울 송파구 백제고분로 236  
2     20  서울 송파구 백제고분로 236  
3     20  서울 송파구 백제고분로 236  
4     17  서울 송파구 백제고분로 236  
5     18  서울 송파구 백제고분로 236  
6     17  서울 송파구 백제고분로 236  
7     20  서울 송파구 백제고분로 236  
8     22  서울 송파구 백제고분로 236  
9     16  서울 송파구 백제고분로 236  
10    15  서울 송파구 백제고분로 236  
11    11  서울 송파구 백제고분로 236  
12    13  서울 송파구 백제고분로 236  
13    14  서울 송파구 백제고분로 236  
14    10  서울 송파구 백제고분로 236  
15    11  서울 송파구 백제고분로 236  
16    10  서울 송파구 백제고분로 236  
17    11  서울 송파구 백제고분로 236  
18    10  서울 송파구 백제고분로 236  
19     8  서울 송파구 백제고분로 236  
20     9  서울 송파구 백제고분로 236  
21     9  서울 송파구 백제고분로 236  
22    14  서울 송파구 백제고분로 236  
23    12  서울 송파구 백제고분로 236  
24    15  서울 송파구 백제고분로 236  
25    11  서울 송파구 백제고분로 236  
26    10  서울 송파구 백제고분로 236  
27    11  서울 송파구 백제고분로 236  
28    13  서울 송파구 백제고분로 236  
29    11  서울 송파구 백제고분로 236  
30     9  서울 송파구 백제고분로 236  
31    12  서울 송파구 백제고분로 236

In [93]:
nation=pd.read_excel('data/nation.xlsx')
code=pd.read_excel('data/code.xlsx')
nation
code

국적코드  국적명
0  A01  필리핀
1  A02   일본
2  A03   미국
3  A04   중국
4  A05   호주
5  A06  베트남
6  A07  스위스
7  A99   기타

In [94]:
merge_df=pd.merge(nation,code,on='국적코드')
merge_df

국적코드  성별    입국객수    증가수  국적명
0  A01  남성  125000   8000  필리핀
1  A01  여성  130000  10000  필리핀
2  A05  남성     300     10   호주
3  A05  여성     200     50   호주
4  A06  남성  158912  24486  베트남
5  A06  여성  325000  63466  베트남

In [95]:
merge_df2=pd.merge(nation, code, how='right', on='국적코드')
merge_df2

국적코드   성별      입국객수      증가수  국적명
0   A01   남성  125000.0   8000.0  필리핀
1   A01   여성  130000.0  10000.0  필리핀
2   A02  NaN       NaN      NaN   일본
3   A03  NaN       NaN      NaN   미국
4   A04  NaN       NaN      NaN   중국
5   A05   남성     300.0     10.0   호주
6   A05   여성     200.0     50.0   호주
7   A06   남성  158912.0  24486.0  베트남
8   A06   여성  325000.0  63466.0  베트남
9   A07  NaN       NaN      NaN  스위스
10  A99  NaN       NaN      NaN   기타

In [99]:
bank_df=pd.read_csv("data/bank.csv")
bank_df
group1=bank_df.groupby(['job','y'])['balance'].sum()
group1

job            y  
admin.         no      824869
               yes     125172
blue-collar    no     1537917
               yes     107557
entrepreneur   no      240510
               yes      43089
housemaid      no      261691
               yes      35653
management     no     2254900
               yes     432801
retired        no      521691
               yes     241699
self-employed  no      383724
               yes      45761
services       no      631729
               yes      47525
student        no      205584
               yes      70194
technician     no     1255184
               yes     236072
unemployed     no      306650
               yes      53179
Name: balance, dtype: int64

In [100]:
group2=bank_df.groupby('job')['balance'].agg(['sum','mean','median','count'])
group2

sum         mean  median  count
job                                               
admin.          950041  1139.137890   368.0    834
blue-collar    1645474  1097.714476   387.0   1499
entrepreneur    283599  1186.606695   313.0    239
housemaid       297344  1429.538462   478.5    208
management     2687701  1722.885256   604.0   1560
retired         763390  2174.900285   927.0    351
self-employed   429485  1677.675781   504.5    256
services        679254  1027.615734   307.0    661
student         275778  1802.470588   459.0    153
technician     1491256  1236.530680   419.0   1206
unemployed      359829  1613.582960   687.0    223

In [ ]:
group3=bank_df.groupby('job').agg({'balance':['sum','mean'],'duration':['mean','count']})

weather에서 date를 datetime으로 형변환한다.
year,month,day 필드를 생성한다.
월별, temp의 중앙값, mean_wind의 평균을 구한다.

In [ ]:
weather_df=pd.read_csv("data/weather.csv")


date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [107]:
weather_df['date'] = pd.to_datetime(weather_df['date'])
weather_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3653 entries, 0 to 3652
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   date       3653 non-null   datetime64[ns]
 1   temp       3653 non-null   float64       
 2   max_wind   3649 non-null   float64       
 3   mean_wind  3647 non-null   float64       
dtypes: datetime64[ns](1), float64(3)
memory usage: 114.3 KB


In [108]:
weather_df['year']=weather_df['date'].dt.year
weather_df['month']=weather_df['date'].dt.month
weather_df['day']=weather_df['date'].dt.day
weather_df

date  temp  max_wind  mean_wind  year  month  day
0    2010-08-01  28.7       8.3        3.4  2010      8    1
1    2010-08-02  25.2       8.7        3.8  2010      8    2
2    2010-08-03  22.1       6.3        2.9  2010      8    3
3    2010-08-04  25.3       6.6        4.2  2010      8    4
4    2010-08-05  27.2       9.1        5.6  2010      8    5
...         ...   ...       ...        ...   ...    ...  ...
3648 2020-07-27  22.1       4.2        1.7  2020      7   27
3649 2020-07-28  21.9       4.5        1.6  2020      7   28
3650 2020-07-29  21.6       3.2        1.0  2020      7   29
3651 2020-07-30  22.9       9.7        2.4  2020      7   30
3652 2020-07-31  25.7       4.8        2.5  2020      7   31

[3653 rows x 7 columns]